//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int masanpham { get; set; }
        public string anh { get; set; }
        public string tensanpham { get; set; }
        public string mota { get; set; }
        public string gia { get; set; }
        public Nullable<int> madanhmucsanpham { get; set; }
    
        public virtual danhmucsanpham danhmucsanpham { get; set; }
    }
}
